version: '3'
services:
  app:
    volumes:
      - nfsmount_src:/home/node/app/src
      - nfsmount_db:/home/node/app/db
      - nfsmount_misc:/home/node/app/misc

volumes:
  nfsmount_src:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}/src/"

  nfsmount_db:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}/db/"

  nfsmount_misc:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}/misc/"
