env: production
node_env: production
repo: git@github.com:Sappchain-OU/sappchat-backend.git
port: 80

# Configuration from terraform output
aws_region: eu-west-2
aws_s3_bucket: sappchat-production-files
cluster: sappchat-production

image_name: sappchat-backend
image_repository: 890991044668.dkr.ecr.eu-west-2.amazonaws.com/sappchat-backend
task_role_arn: arn:aws:iam::890991044668:role/ecs/sappchat-staging-task-role
execution_role_arn: arn:aws:iam::890991044668:role/ecs/sappchat-staging-execution-role

subnets: ['subnet-0c2d4cb5e298ed4c5', 'subnet-0d6e7c8d6c265a087']
security_groups: ['sg-0ca5db86e3714e087']

# App container configuration
app_cpu: 2048
app_memory: 4096
app_container_cpu: 2048
app_container_memory: 4096
app_desired_count: 1

# Non-sensitive vars
cors_origin: "*"
app_sentry_dsn: "https://c193c1e0140d4d479111d828657167c7@o554597.ingest.sentry.io/5683394"
app_web3_fee_address: "0x6185990909092F832B993c9ceF5A048b8a1C054E"
app_database_logging_disabled: "false"
